import contextlib
import os
from pathlib import Path
from typing import List

import uvicorn
from mcp.server.fastmcp import FastMCP
from starlette.applications import Starlette

from starlette.routing import Mount

from service.sandbox_manager import SandboxManager


APP_ROOT = Path(__file__).resolve().parent.parent
SANDBOX_ROOT = Path(os.environ.get("SANDBOX_ROOT", str(APP_ROOT / "sandboxes"))).resolve()
DOCKER_IMAGE = os.environ.get("SANDBOX_PYTHON_IMAGE", "sandbox-python")
CONTAINER_PREFIX = os.environ.get("SANDBOX_CONTAINER_PREFIX", "code-sandbox")
WORKDIR_IN_CONTAINER = "/workspace"
NETWORK_DISABLED = os.environ.get("SANDBOX_NETWORK_DISABLED", "0").lower() in ("1", "true", "yes")

MCP_HOST = os.environ.get("MCP_HOST", "0.0.0.0")
MCP_PORT = int(os.environ.get("MCP_PORT", "3000"))

manager = SandboxManager(
    sandbox_root=SANDBOX_ROOT,
    docker_image=DOCKER_IMAGE,
    container_prefix=CONTAINER_PREFIX,
    workdir_in_container=WORKDIR_IN_CONTAINER,
    network_disabled=NETWORK_DISABLED,
)

mcp = FastMCP(
    "Pandora Sandbox",
    instructions="Docker-backed sandbox manager for running Python code generated by AI agents.",
    stateless_http=True,
    json_response=True,
    host=MCP_HOST
)


@mcp.tool()
def create_sandbox(sandbox_name: str ) -> dict:
    """Create a new sandbox.

    Args:
    - sandbox_name: short meaningful name for the sandbox (will be sanitized and appended to the ID)

    Creates:
    - A sandbox workspace directory on host
    - A dedicated Docker container with workspace bind-mounted

    Returns:
    - id: sandbox identifier
    
    Errors:
    - error: error message if creation fails
    """

    try:
        sandbox_id = manager.create_sandbox(sandbox_name)
        return {"success": True, "id": sandbox_id}
    except Exception as e:
        return {"success": False, "error": str(e), "error_type": type(e).__name__}


@mcp.tool()
def delete_sandbox(id: str) -> dict:
    """Delete a sandbox and clean up all resources.

    Removes:
    - The Docker container for the sandbox
    - The sandbox workspace directory (including uploaded files and installed packages)
    
    Errors:
    - error: error message if deletion fails
    """

    try:
        manager.delete_sandbox(id)
        return {"success": True, "message": "Sandbox deleted successfully"}
    except Exception as e:
        return {"success": False, "error": str(e), "error_type": type(e).__name__}


@mcp.tool()
def sandbox_upsert_file(sandbox_id: str, path: str, content: str) -> dict:
    """Create or update a file in the sandbox workspace.
    
    Args:
    - sandbox_id: sandbox identifier
    - path: path to the file in the sandbox workspace
    - content: file content as text
    
    Errors:
    - error: error message if file operation fails
    """

    try:
        manager.upsert_file(sandbox_id, path, content)
        return {"success": True, "message": f"File '{path}' created/updated successfully"}
    except Exception as e:
        return {"success": False, "error": str(e), "error_type": type(e).__name__}


@mcp.tool()
def sandbox_delete_file(sandbox_id: str, path: str) -> dict:
    """Delete a file from the sandbox workspace.
    
    Args:
    - sandbox_id: sandbox identifier
    - path: path to the file in the sandbox workspace
    
    Errors:
    - error: error message if deletion fails
    """

    try:
        manager.delete_file(sandbox_id, path)
        return {"success": True, "message": f"File '{path}' deleted successfully"}
    except Exception as e:
        return {"success": False, "error": str(e), "error_type": type(e).__name__}


@mcp.tool()
def sandbox_execute_bash(sandbox_id: str, command: str) -> dict:
    """Execute a bash command inside a sandbox.
    
    This is a general-purpose tool that can run any command in the sandbox.
    Use 'ls', 'mkdir', 'rm', 'python', 'pip', 'curl', etc. as the command.
    
    Note: Use 'tail' to read files in large chunks to avoid overwhelming output.
    For reading 50 lines starting at line X: tail -n +X filename | head -n 50
    Always use 'tail' with at least 20 lines (e.g., tail -n 20 filename).

    Args:
    - sandbox_id (str): sandbox identifier
    - command (str): the bash command to execute (e.g., 'python script.py', 'ls -la', 'pip install requests')

    Returns:
    - exit_code, stdout, stderr

    Errors:
    - error: error message if execution fails
    """
    try:
        # Reject 'cat' command and suggest using tail instead
        if "cat" in command.lower():
            return {
                "success": False,
                "exit_code": 1,
                "stdout": "",
                "stderr": "Use 'tail' to read files in large chunks instead. Example: tail -n +X filename | head -n 50 (reads 50 lines starting at line X)",
                "message": "cat command not allowed"
            }
        
        # Check for args exceeding 500 characters
        if len(command) > 500:
            return {
                "success": False,
                "exit_code": 1,
                "stdout": "",
                "stderr": "commandline argument too long. If executing code, put the code in a file and upsert the file first.",
                "message": "Argument length exceeds 500 characters, can bloat your context window."
            }
        
        exit_code, stdout, stderr = manager.execute(sandbox_id, command, [])
        
        # Check for stdout/stderr exceeding 3000 characters
        if len(stdout) > 3000:
            return {
                "success": False,
                "exit_code": exit_code,
                "stdout": "",
                "stderr": "output too long. Write the output to a file when executing the bash command and read it using tail few lines at a time. Example: tail -n +X filename | head -n 50 (reads 50 lines starting at line X)",
                "message": "Output length exceeds 3000 characters, can bloat your context window."
            }
        if len(stderr) > 3000:
            return {
                "success": False,
                "exit_code": exit_code,
                "stdout": "",
                "stderr": "It is mandatory to execute the command again and Write the output to a file when executing the bash command and read it using tail few lines at a time. Example: tail -n +X filename | head -n 50 (reads 50 lines starting at line X)",
                "message": "length of stderr exceeds 3000 characters, might bloat your context window."
            }
        
        return {
            "success": True,
            "exit_code": exit_code,
            "stdout": stdout,
            "stderr": stderr,
            "message": "Execution completed"
        }
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "error_type": type(e).__name__,
            "exit_code": -1,
            "stdout": "",
            "stderr": str(e)
        }


@mcp.tool()
def sandbox_read_file(
    sandbox_id: str,
    file_path: str,
    offset: int,
    limit: int,
) -> str:
    """Read file content from a sandbox filesystem with mandatory offset and limit.

    Args:
        sandbox_id: Sandbox identifier
        file_path: Relative path to the file inside the sandbox workspace
        offset: Line number to start reading from (0-based)
        limit: Maximum number of lines to read (capped at 50)

    Returns:
        Formatted file content with line numbers, or an error message if the file is not found
    """
    return manager.read_file(sandbox_id, file_path, offset, limit)


@mcp.tool()
def sandbox_edit_file(
    file_path: str,
    old_string: str,
    new_string: str,
    sandbox_id: str,
    replace_all: bool = False,
) -> str:
    """Perform exact string replacements in files.

    Usage:
    - You must use your `sandbox_read_file` tool at least once in the conversation before editing.
      This tool will error if you attempt an edit without reading the file.
    - When editing text from Read tool output, ensure you preserve the exact indentation (tabs/spaces)
      as it appears AFTER the line number prefix. The line number prefix format is: spaces + line number + tab.
      Everything after that tab is the actual file content to match. Never include any part of the
      line number prefix in the old_string or new_string.
    - ALWAYS prefer editing existing files. NEVER write new files unless explicitly required.
    - Only use emojis if the user explicitly requests it. Avoid adding emojis to files unless asked.
    - The edit will FAIL if `old_string` is not unique in the file. Either provide a larger string
      with more surrounding context to make it unique or use `replace_all` to change every instance.
    - Use `replace_all` for replacing and renaming strings across the file. This parameter is useful
      if you want to rename a variable for instance.

    Args:
        file_path: Relative path to the file inside the sandbox workspace
        old_string: The exact string to find and replace
        new_string: The replacement string
        sandbox_id: Sandbox identifier
        replace_all: If True, replace every occurrence of old_string (default: False)

    Returns:
        Success message with replacement count, or an error message
    """
    return manager.edit_file(sandbox_id, file_path, old_string, new_string, replace_all)


@mcp.tool()
def list_running_sandboxes() -> dict:
    """List all running sandboxes with their status and metadata.
    
    Returns:
    - sandboxes: list of sandbox information including:
      - id: sandbox identifier
      - container_name: Docker container name
      - status: container status (running, exited, etc.)
      - created: container creation timestamp
      - directory_exists: whether the sandbox directory exists on the host
      - image: Docker image used for the sandbox
    
    Errors:
    - error: error message if listing fails
    """

    try:
        sandboxes = manager.list_running_sandboxes()
        return {
            "success": True,
            "sandboxes": sandboxes,
            "count": len(sandboxes),
            "message": f"Found {len(sandboxes)} sandbox(es)"
        }
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "error_type": type(e).__name__,
            "sandboxes": [],
            "count": 0
        }


@contextlib.asynccontextmanager
async def lifespan(app: Starlette):
    async with mcp.session_manager.run():
        yield


if not hasattr(mcp, "streamable_http_app"):
    raise RuntimeError(
        "Installed 'mcp' package does not support Streamable HTTP. "
        "Upgrade to a newer MCP Python SDK (e.g. 'mcp>=1.2.0')."
    )

app = Starlette(
    routes=[
        Mount("/", app=mcp.streamable_http_app()),
    ],
    lifespan=lifespan,
    )


def main() -> None:
    # Verify Docker image exists before starting
    import subprocess
    result = subprocess.run(
        ["docker", "image", "inspect", DOCKER_IMAGE],
        capture_output=True,
        text=True
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"Docker image '{DOCKER_IMAGE}' not found. "
            f"Please build the image before starting the server."
        )

    # Configure uvicorn to allow requests from any host
    # Set environment variable to disable host validation
    os.environ["PYTHONUNBUFFERED"] = "1"
    
    uvicorn.run(
        app, 
        host=MCP_HOST, 
        port=MCP_PORT,
        # Allow requests from any IP/host - disable strict host checking
        server_header=False,
        access_log=False,
        # Additional settings to allow cross-origin and host header flexibility
        ws_ping_interval=None,
        ws_ping_timeout=None,
    )


if __name__ == "__main__":
    main()
