import contextlib
import os
from pathlib import Path
from typing import List

import uvicorn
from mcp.server.fastmcp import FastMCP
from starlette.applications import Starlette

from starlette.routing import Mount

from service.sandbox_manager import SandboxManager


APP_ROOT = Path(__file__).resolve().parent.parent
SANDBOX_ROOT = Path(os.environ.get("SANDBOX_ROOT", str(APP_ROOT / "sandboxes"))).resolve()
DOCKER_IMAGE = os.environ.get("SANDBOX_PYTHON_IMAGE", "sandbox-python")
CONTAINER_PREFIX = os.environ.get("SANDBOX_CONTAINER_PREFIX", "code-sandbox")
WORKDIR_IN_CONTAINER = "/workspace"
NETWORK_DISABLED = os.environ.get("SANDBOX_NETWORK_DISABLED", "0").lower() in ("1", "true", "yes")

MCP_HOST = os.environ.get("MCP_HOST", "0.0.0.0")
MCP_PORT = int(os.environ.get("MCP_PORT", "3000"))

manager = SandboxManager(
    sandbox_root=SANDBOX_ROOT,
    docker_image=DOCKER_IMAGE,
    container_prefix=CONTAINER_PREFIX,
    workdir_in_container=WORKDIR_IN_CONTAINER,
    network_disabled=NETWORK_DISABLED,
)

mcp = FastMCP(
    "Pandora Sandbox",
    instructions="Docker-backed sandbox manager for running Python code generated by AI agents.",
    stateless_http=True,
    json_response=True,
    host=MCP_HOST
)


@mcp.tool()
def create_sandbox(sandbox_name: str ) -> dict:
    """Create a new sandbox.

    Args:
    - sandbox_name: short meaningful name for the sandbox (will be sanitized and appended to the ID)

    Creates:
    - A sandbox workspace directory on host
    - A dedicated Docker container with workspace bind-mounted

    Returns:
    - id: sandbox identifier
    
    Errors:
    - error: error message if creation fails
    """

    try:
        sandbox_id = manager.create_sandbox(sandbox_name)
        return {"success": True, "id": sandbox_id}
    except Exception as e:
        return {"success": False, "error": str(e), "error_type": type(e).__name__}


@mcp.tool()
def delete_sandbox(id: str) -> dict:
    """Delete a sandbox and clean up all resources.

    Removes:
    - The Docker container for the sandbox
    - The sandbox workspace directory (including uploaded files and installed packages)
    
    Errors:
    - error: error message if deletion fails
    """

    try:
        manager.delete_sandbox(id)
        return {"success": True, "message": "Sandbox deleted successfully"}
    except Exception as e:
        return {"success": False, "error": str(e), "error_type": type(e).__name__}


@mcp.tool()
def execute(sandbox_id: str, command: str, args: List[str] | None = None) -> dict:
    """Execute a bash command inside a sandbox.
    
    This is a general-purpose tool that can run any command in the sandbox.
    Use 'ls', 'cat', 'mkdir', 'rm', 'python', 'pip', 'curl', etc. as the command.

    Args:
    - sandbox_id: sandbox identifier
    - command: the bash command to execute (e.g., 'python', 'ls', 'cat', 'mkdir')
    - args: command-line arguments passed to the command

    Returns:
    - exit_code, stdout, stderr
    
    Errors:
    - error: error message if execution fails
    """
    try:
        exit_code, stdout, stderr = manager.execute(sandbox_id, command, args or [])
        return {
            "success": True,
            "exit_code": exit_code,
            "stdout": stdout,
            "stderr": stderr,
            "message": "Execution completed"
        }
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "error_type": type(e).__name__,
            "exit_code": -1,
            "stdout": "",
            "stderr": str(e)
        }


@mcp.tool()
def list_running_sandboxes() -> dict:
    """List all running sandboxes with their status and metadata.
    
    Returns:
    - sandboxes: list of sandbox information including:
      - id: sandbox identifier
      - container_name: Docker container name
      - status: container status (running, exited, etc.)
      - created: container creation timestamp
      - directory_exists: whether the sandbox directory exists on the host
      - image: Docker image used for the sandbox
    
    Errors:
    - error: error message if listing fails
    """

    try:
        sandboxes = manager.list_running_sandboxes()
        return {
            "success": True,
            "sandboxes": sandboxes,
            "count": len(sandboxes),
            "message": f"Found {len(sandboxes)} sandbox(es)"
        }
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "error_type": type(e).__name__,
            "sandboxes": [],
            "count": 0
        }


@contextlib.asynccontextmanager
async def lifespan(app: Starlette):
    async with mcp.session_manager.run():
        yield


if not hasattr(mcp, "streamable_http_app"):
    raise RuntimeError(
        "Installed 'mcp' package does not support Streamable HTTP. "
        "Upgrade to a newer MCP Python SDK (e.g. 'mcp>=1.2.0')."
    )

app = Starlette(
    routes=[
        Mount("/", app=mcp.streamable_http_app()),
    ],
    lifespan=lifespan,
    )


def main() -> None:
    # Verify Docker image exists before starting
    import subprocess
    result = subprocess.run(
        ["docker", "image", "inspect", DOCKER_IMAGE],
        capture_output=True,
        text=True
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"Docker image '{DOCKER_IMAGE}' not found. "
            f"Please build the image before starting the server."
        )

    # Configure uvicorn to allow requests from any host
    # Set environment variable to disable host validation
    os.environ["PYTHONUNBUFFERED"] = "1"
    
    uvicorn.run(
        app, 
        host=MCP_HOST, 
        port=MCP_PORT,
        # Allow requests from any IP/host - disable strict host checking
        server_header=False,
        access_log=False,
        # Additional settings to allow cross-origin and host header flexibility
        ws_ping_interval=None,
        ws_ping_timeout=None,
    )


if __name__ == "__main__":
    main()
